In [ ]:
'''Q. Mini Data Cleaning + Analysis Problem

Given a CSV containing:

CustomerID
Name
Age
Gender
City
Income
PurchaseAmount


load the CSV
inspect the data
check data types
check missing values
remove duplicates
handle missing values
filter customers based on income
calculate average purchase amount
find the highest-spending customer
find city-wise average purchase
find gender-wise average income
sort customers by purchase amount
create a new category based on purchase amount
save the cleaned DataFrame as a new CSV'''

In [1]:
import pandas as pd
df=pd.read_csv("raw_data.csv")

In [2]:
df.shape

(11, 6)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     str
 2   age      8 non-null      float64
 3   country  10 non-null     str
 4   gender   10 non-null     str
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), str(3)
memory usage: 849.0 bytes

In [4]:
df.size

66

In [5]:
df.describe()

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [6]:
df.columns

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='str')

In [7]:
df.dtypes

id           int64
name           str
age        float64
country        str
gender         str
income     float64
dtype: object

In [8]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [9]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [10]:
df=df.drop_duplicates()

In [11]:
df.duplicated()

0     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [12]:
df.reset_index(drop=True)

   id          name   age country   gender   income
0   1      John Doe  29.0     USA     Male  55000.0
1   2    Jane Smith   NaN  Canada   Female  62000.0
2   3          Alex   NaN     USA  Unknown  47000.0
3   4  Maria Garcia  34.0   Spain   Female      NaN
4   5        Li Wei  27.0   China     Male  51000.0
5   6           NaN  45.0   India   Female  73000.0
6   7    Ahmed Khan  38.0     NaN     Male  68000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   9   Carlos Ruiz   NaN  Mexico     Male  45000.0
9  10   Emily Davis  31.0     USA      NaN  58000.0

In [13]:
df['age']=df['age'].fillna(df['age']).mean()

In [14]:
df['income']=df['income'].fillna(df['income'].mean())

In [15]:
df.isnull().sum()

id         0
name       1
age        0
country    1
gender     1
income     0
dtype: int64

In [16]:
df1=df.dropna()

In [17]:
df1

   id          name        age country   gender        income
0   1      John Doe  33.285714     USA     Male  55000.000000
2   2    Jane Smith  33.285714  Canada   Female  62000.000000
3   3          Alex  33.285714     USA  Unknown  47000.000000
4   4  Maria Garcia  33.285714   Spain   Female  57888.888889
5   5        Li Wei  33.285714   China     Male  51000.000000
8   8    Rachel Lee  33.285714     USA   Female  62000.000000
9   9   Carlos Ruiz  33.285714  Mexico     Male  45000.000000

In [19]:
df1.groupby('country')['income'].mean()

country
Canada    62000.000000
China     51000.000000
Mexico    45000.000000
Spain     57888.888889
USA       54666.666667
Name: income, dtype: float64

In [21]:
print(df1['income'].mean())

54269.841269841265

In [22]:
print(df1["income"].max())

62000.0

In [23]:
df1.groupby("gender")["income"].mean()

gender
Female     60629.629630
Male       50333.333333
Unknown    47000.000000
Name: income, dtype: float64

In [24]:
sorted=df1.sort_values('income')

In [25]:
s1=sorted.reset_index(drop=True)

In [27]:
s2=s1.drop(['id'],axis=1)

In [28]:
s2

           name        age country   gender        income
0   Carlos Ruiz  33.285714  Mexico     Male  45000.000000
1          Alex  33.285714     USA  Unknown  47000.000000
2        Li Wei  33.285714   China     Male  51000.000000
3      John Doe  33.285714     USA     Male  55000.000000
4  Maria Garcia  33.285714   Spain   Female  57888.888889
5    Jane Smith  33.285714  Canada   Female  62000.000000
6    Rachel Lee  33.285714     USA   Female  62000.000000