# NUMPY

In [11]:
'''Create a NumPy array containing numbers from 1 to 20. Print its ndim, shape, size, and dtype.'''
import numpy as np
arr1=np.array(list(map(int,input().split(","))))
arr2=np.array(list(map(int,input().split(","))))
arr=np.array([arr1,arr2])
print(arr)

 1,2,3,4,5
 6,7,8,9,1

[[1 2 3 4 5]
 [6 7 8 9 1]]

In [12]:
print(type(arr))

<class 'numpy.ndarray'>

In [16]:
print(arr.size)
arr.shape

10

(2, 5)

In [17]:
print(arr.ndim)
arr.dtype

2

dtype('int64')

In [19]:
arr3=np.arange(1,20,2)
print(arr3)

[ 1  3  5  7  9 11 13 15 17 19]

In [23]:
'''Create a 3 × 4 NumPy array containing numbers from 1 to 12. Print the first row, last row, first column, and last column.'''
arr=np.array([np.arange(1,8,2),np.arange(3,10,2),np.arange(4,11,2)])
print(arr)

[[ 1  3  5  7]
 [ 3  5  7  9]
 [ 4  6  8 10]]

In [30]:
print(arr[0])
print(arr[2])
print(arr[0:3,0])
print(arr[0:3,3])
arr.shape

[1 3 5 7]
[ 4  6  8 10]
[1 3 4]
[ 7  9 10]

(3, 4)

In [31]:
'''Create an array of numbers from 10 to 50 with a gap of 5 using arange(). Then create 10 equally spaced numbers between 0 and 1 using linspace().'''
arr=np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]

In [33]:
arr=np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

In [36]:
'''Given:

arr = np.arange(1, 13)

Reshape it into 2 × 6, 3 × 4, and 4 × 3 arrays.'''
arr=np.arange(1,13)
reshaped1=arr.reshape(2,6)
reshaped2=arr.reshape(3,4)
reshaped3=arr.reshape(4,3)

In [37]:
print(reshaped1)
print(reshaped2)
print(reshaped3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

In [43]:
'''Given a 2-D array, extract:

first two rows
last two columns
alternate rows
alternate columns
reverse the entire array'''
arr=np.array([np.arange(11,16),np.arange(1,6)])
print(arr)

[[11 12 13 14 15]
 [ 1  2  3  4  5]]

In [46]:
arr[:]

array([[11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5]])

In [47]:
arr[:,3:]

array([[14, 15],
       [ 4,  5]])

In [48]:
arr[:,::2]

array([[11, 13, 15],
       [ 1,  3,  5]])

In [49]:
arr[::-1,::-1]

array([[ 5,  4,  3,  2,  1],
       [15, 14, 13, 12, 11]])

In [95]:
'''Given:

arr = np.array([10, 25, 30, 45, 50, 65, 70])

Extract all values greater than 40, all even values, and all values between 25 and 65.

'''
arr = np.array([10, 25, 30, 45, 50, 65, 70])
l=[]
for value in arr:
    #print(value)
    if value>40:
        print(value)

45
50
65
70

In [93]:
for value in arr:
    if value%2==0:
        print(value)

10
20
30
40
50

In [94]:
for value in arr:
    if 25<value<65:
        print(value)

30
40
50

In [91]:
'''Given:

arr = np.array([10, 20, 30, 40, 50])

Calculate the sum, mean, median, minimum, maximum, variance, and standard deviation.'''
arr = np.array([10, 20, 30, 40, 50])
print(arr.sum())
print(arr.mean())
#print(arr.median())
print(arr.min())
print(arr.max())
mean=arr.mean()
std=arr.std()
normalized_arr=(arr-mean)/std
print(normalized_arr)

150
30.0
10
50
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [92]:
arr = np.array([10, 20, 30, 40, 50])
add=0
for num in arr:
    add+=num
print(add)

150

In [83]:
num=list(map(int,input().split(",")))
add=0
n=len(num)
'''for i in num:
    add+=i
print(f"mean{add/n}")'''

if n%2==0:
    median=(num[n//2-1]+num[n//2])/2
else:
    median=num[n//2]
    
print(median)

 10,20,30,40

25.0

In [110]:
'''Given:

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

Calculate the sum and mean using axis=0 and axis=1.'''
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
sum_of_column=np.sum(arr,axis=0)
sum_of_rows=np.sum(arr,axis=1)
mean_of_column=np.mean(arr,axis=0)
mean_of_rows=np.mean(arr,axis=1)

In [111]:
print(sum_of_column)
print(sum_of_rows)
print(mean_of_column)
print(mean_of_rows)

[120 150 180]
[ 60 150 240]
[40. 50. 60.]
[20. 50. 80.]

In [113]:
'''Given:

arr = np.array([5, 10, 15, 20, 25])

Use broadcasting to:

add 10
subtract 5
multiply by 2
divide by 5'''
add_10=arr*10
sub_5=arr-5
mul_2=arr*2
div_5=arr/5
print(add_10)
print(sub_5)
print(mul_2)
print(div_5)

[[100 200 300]
 [400 500 600]
 [700 800 900]]
[[ 5 15 25]
 [35 45 55]
 [65 75 85]]
[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

In [4]:
import numpy as np
x=np.arange(5)
width=0.35
print(x-width)

[-0.35  0.65  1.65  2.65  3.65]

In [8]:
'''Given:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

Find the result of element-wise multiplication and dot/matrix multiplication. Explain the difference.'''
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a*b)
print(np.dot(a,b))
''' * performs element-wise multiplication, while @ performs matrix multiplication.
In element-wise multiplication, corresponding elements are multiplied; in matrix multiplication, rows are multiplied by columns.'''

[ 4 10 18]
32

'* performs element-wise multiplication, while @ performs matrix multiplication.\nIn element-wise multiplication, corresponding elements are multiplied; in matrix multiplication, rows are multiplied by columns.'

In [14]:
'''Given:

arr = np.array([10, 20, 10, 30, 20, 40, 30, 30])

Find all unique values and the frequency/count of each value.'''
import numpy as np
arr = np.array([10, 20, 10, 30, 20, 40, 30, 30])
value,count=np.unique(arr,return_counts=True)
print(value)
print(count)

[10 20 30 40]
[2 2 3 1]

In [17]:
'''Given:

arr = np.array([45, 12, 89, 34, 67, 23])

Find:

sorted array
indexes that would sort the array
index of maximum value
index of minimum value'''
arr = np.array([45, 12, 89, 34, 67, 23])
sorted=np.sort(arr)
indexes=np.argsort(arr)

In [20]:
print(sorted)
print(indexes)
print(np.argmax(arr))
print(np.argmin(arr))

[12 23 34 45 67 89]
[1 5 3 0 4 2]
2
1

In [23]:
'''Given:

arr = np.array([10, 20, 30, 40, 50])

Use np.where() to:

find indexes of values greater than 25
replace values greater than 25 with 100'''
arr = np.array([10, 20, 30, 40, 50])
indexes=np.where(arr>25)
print(indexes)
arr[np.where(arr>25)]=100
print(arr)

(array([2, 3, 4]),)
[ 10  20 100 100 100]

In [45]:
'''Create two NumPy arrays:

[1,2,3,4]
[5,6,7,8]

Combine them using concatenate, vertical stacking, and horizontal stacking.'''
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))
vertical=np.vstack((a,b))
print(vertical)
horizontal=np.hstack((a,b))
print(horizontal)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]

In [49]:
'''Given a 3 × 6 array, split it into:

3 equal horizontal parts
2 equal vertical parts'''

arr=np.array([np.arange(1,7),np.arange(3,9),np.arange(4,10)])
print(arr)
arr.shape

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]
 [4 5 6 7 8 9]]

(3, 6)

In [54]:
print(arr[:])

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]
 [4 5 6 7 8 9]]

In [59]:
arr[:,:3],arr[:,3:]

(array([[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]]),
 array([[4, 5, 6],
        [6, 7, 8],
        [7, 8, 9]]))

In [63]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [69]:
np.linspace(1,9,3)

array([1., 5., 9.])

In [96]:
'''Create a 3 × 3 matrix and demonstrate the difference between:

copy()
view/reference
Modify the new array and observe what happens to the original.'''

l = [1,2,3,4,5]

print(l)
sli=l[:3]
sli[0]=100
print(sli)
print(l)
print(type(l))

[1, 2, 3, 4, 5]
[100, 2, 3]
[1, 2, 3, 4, 5]
<class 'list'>

In [87]:
arr=np.array(l)
print(type(arr))
sli2=arr[:3]
sli2[0]=100
print(sli2)
print(arr)

<class 'numpy.ndarray'>
[100  20  30]
[100  20  30  40  50]

In [102]:
'''Given:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

Convert it into a 1-D array using both flattening methods and determine whether changes affect the original array.'''
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
flattened=arr.flatten()
print(flattened)
reshaped=flattened.reshape(2,3)
print(reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]

In [111]:
'''Create a 5 × 5 matrix of random integers between 1 and 100. Find its minimum, maximum, mean, and standard deviation.'''
arr=np.arange(1,26).reshape(5,5)
print(arr)
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
1
25
13.0
7.211102550927978

# PANDAS

In [119]:
'''1. Pandas Basics

Create a Pandas Series from:

[10, 20, 30, 40, 50]

Then create a DataFrame containing student names, ages, and marks. Display the Series and DataFrame.'''

import pandas as pd
l=[10, 20, 30, 40, 50]
df=pd.Series(l,index=['A','B','C','D','E'])
print(type(df))
print(df)

<class 'pandas.Series'>
A    10
B    20
C    30
D    40
E    50
dtype: int64

In [124]:
df1=pd.DataFrame({
    "names":["deepak","rahul","akash","arti"],
    "ages":[20,30,40,50],
    "marks":[80,85,90,95]
        
}
)
print(df1)

    names  ages  marks
0  deepak    20     80
1   rahul    30     85
2   akash    40     90
3    arti    50     95

In [134]:
'''2. DataFrame Information

Given a DataFrame, find:

number of rows and columns
column names
data types
total number of elements
index
memory usage

Use appropriate Pandas functions.'''
df=({
    "Name":["a","b","c","d"],
    "Age":[10,20,30,40],
    "Marks":[70,75,80,85]
})
print(type(df))

<class 'dict'>

In [135]:
data=pd.DataFrame(df)
print(data)

  Name  Age  Marks
0    a   10     70
1    b   20     75
2    c   30     80
3    d   40     85

In [159]:
rows=data.shape[0]
columns=data.shape[1]
print(rows)
print(columns)
print(data.columns)

4
3
Index(['Name', 'Age', 'Marks'], dtype='str')

In [164]:
data.dtypes

Name       str
Age      int64
Marks    int64
dtype: object

In [166]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [167]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 232.0 bytes

In [168]:
data.nunique()

Name     4
Age      4
Marks    4
dtype: int64

In [3]:
'''3. Reading and Saving Data

Create a DataFrame and:

save it as a CSV file
read the CSV file back
display the first 5 and last 5 rows'''
import pandas as pd
df=({
    "Name":["a","b","c","d"],
    "Age":[10,20,30,40],
    "Marks":[70,75,80,85]
})
df2=pd.DataFrame(df)
save=df2.to_csv("data.csv",index=False)
df3=pd.read_csv("data.csv")

In [4]:
df3

  Name  Age  Marks
0    a   10     70
1    b   20     75
2    c   30     80
3    d   40     85

In [5]:
df3.head()

  Name  Age  Marks
0    a   10     70
1    b   20     75
2    c   30     80
3    d   40     85

In [8]:
df3.head()
print(df3.tail())

  Name  Age  Marks
0    a   10     70
1    b   20     75
2    c   30     80
3    d   40     85

In [1]:
'''4. Selecting Columns

Given:

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [21, 25, 23, 27],
    "Marks": [78, 65, 90, 55]
})

Select:

only Name
only Marks
Name and Marks
all columns except Age'''

import pandas as pd
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [21, 25, 23, 27],
    "Marks": [78, 65, 90, 55]
})
print(df["Name"])
print(df["Marks"] )

0    A
1    B
2    C
3    D
Name: Name, dtype: str
0    78
1    65
2    90
3    55
Name: Marks, dtype: int64

In [3]:
print(df[["Name","Marks"]])
df1=df.drop(columns=["Age"])
df1

  Name  Marks
0    A     78
1    B     65
2    C     90
3    D     55

  Name  Marks
0    A     78
1    B     65
2    C     90
3    D     55

In [5]:
'''5. Selecting Rows

Using the same DataFrame, select:

first 2 rows
last 2 rows
row at index 2
rows from index 1 to 3

Use both loc and iloc.'''
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [21, 25, 23, 27],
    "Marks": [78, 65, 90, 55]
})
print(df.loc[0:1])
print(df.iloc[0:2])

  Name  Age  Marks
0    A   21     78
1    B   25     65
  Name  Age  Marks
0    A   21     78
1    B   25     65

In [6]:
print(df.loc[2:])
print(df.iloc[2:])

  Name  Age  Marks
2    C   23     90
3    D   27     55
  Name  Age  Marks
2    C   23     90
3    D   27     55

In [9]:
print(df.iloc[2])
print(df.iloc[1:4])

Name      C
Age      23
Marks    90
Name: 2, dtype: object
  Name  Age  Marks
1    B   25     65
2    C   23     90
3    D   27     55

In [10]:
'''6. loc vs iloc

Explain the difference between loc and iloc, then use them to select:

a specific row
a specific column
multiple rows and columns'''
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [21, 25, 23, 27],
    "Marks": [78, 65, 90, 55]
})
#loc- is generally used for finding rows and column using labels.
#iloc- is generally used for finding column using indexes.
print(df.loc[2])
print(df.iloc[3])

Name      C
Age      23
Marks    90
Name: 2, dtype: object
Name      D
Age      27
Marks    55
Name: 3, dtype: object

In [16]:
print(df.loc[:,"Marks"])
print(df.iloc[:,1])

0    78
1    65
2    90
3    55
Name: Marks, dtype: int64
0    21
1    25
2    23
3    27
Name: Age, dtype: int64

In [1]:
'''7. Filtering Data

Given a student DataFrame, find:

students with marks greater than 70
students younger than 25
students with marks between 50 and 80
students whose age is greater than 22 and marks are greater than 60'''
import pandas as pd
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D","E","F"],
    "Age": [21, 25, 23, 27,28,29],
    "Marks": [78, 65, 90, 55,60,70]
})
print(df[df["Marks"]>70])
print(df[df["Age"]<25])

  Name  Age  Marks
0    A   21     78
2    C   23     90
  Name  Age  Marks
0    A   21     78
2    C   23     90

In [13]:
print(df[(df["Marks"]>50)&(df["Marks"]<70)])

  Name  Age  Marks
1    B   25     65
3    D   27     55
4    E   28     60

In [15]:
print(df[(df["Age"]>22)&(df["Marks"]>60)])

  Name  Age  Marks
1    B   25     65
2    C   23     90
5    F   29     70

In [2]:
'''8. Adding, Updating and Deleting Columns

Given a DataFrame containing:

Name | Math | Science

Create a new Total column, then create an Average column.

After that:

update the Average column
delete the Science column'''
data=pd.DataFrame({
    "Name":["A","B","C","D","E"],
    "Math":[10,20,30,40,50],
    "Science":[20,30,40,50,60]
})
data["Total_column"]=3
data["avg"]=25

In [3]:
data

  Name  Math  Science  Total_column  avg
0    A    10       20             3   25
1    B    20       30             3   25
2    C    30       40             3   25
3    D    40       50             3   25
4    E    50       60             3   25

In [4]:
data.assign(avg=data["avg"]*2)

  Name  Math  Science  Total_column  avg
0    A    10       20             3   50
1    B    20       30             3   50
2    C    30       40             3   50
3    D    40       50             3   50
4    E    50       60             3   50

In [5]:
data.drop("Science",axis=1,inplace=True)

In [6]:
data

  Name  Math  Total_column  avg
0    A    10             3   25
1    B    20             3   25
2    C    30             3   25
3    D    40             3   25
4    E    50             3   25

In [7]:
'''9. Sorting Data

Given a DataFrame of students, sort it:

by marks ascending
by marks descending
by age and then marks
using multiple columns with different sorting orders'''
df=pd.DataFrame({
    "Name":["A","B","C","D","E"],
    "Math":[10,20,30,40,50],
    "Science":[20,30,40,50,60]
})
df.sort_values("Math")

  Name  Math  Science
0    A    10       20
1    B    20       30
2    C    30       40
3    D    40       50
4    E    50       60

In [10]:
print(df.sort_values("Math",ascending=False))
print(df.sort_values(["Math","Science"]))

  Name  Math  Science
4    E    50       60
3    D    40       50
2    C    30       40
1    B    20       30
0    A    10       20
  Name  Math  Science
0    A    10       20
1    B    20       30
2    C    30       40
3    D    40       50
4    E    50       60

In [21]:
'''10. Missing Values

Given:

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [21, np.nan, 23, 25],
    "Marks": [80, 70, np.nan, 90]
})

Find:

number of missing values
missing values column-wise
rows containing missing values
fill missing Age with the mean
fill missing Marks with the median'''
import numpy as np
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [21, np.nan, 23, 25],
    "Marks": [80, 70, np.nan, 90]
})
print(df.isnull().sum())
print(df["Age"].isnull())
print(df["Marks"].isnull())

Name     0
Age      1
Marks    1
dtype: int64
0    False
1     True
2    False
3    False
Name: Age, dtype: bool
0    False
1    False
2     True
3    False
Name: Marks, dtype: bool

In [25]:
df["Age"]=df["Age"].fillna(df["Age"].mean())

In [23]:
df

  Name   Age  Marks
0    A  21.0   80.0
1    B  23.0   70.0
2    C  23.0    NaN
3    D  25.0   90.0

In [26]:
df["Marks"]=df["Marks"].fillna(df["Marks"].median())

In [27]:
df

  Name   Age  Marks
0    A  21.0   80.0
1    B  23.0   70.0
2    C  23.0   80.0
3    D  25.0   90.0

In [28]:
'''11. Duplicate Data

Given a DataFrame containing duplicate rows:

find duplicate rows
count duplicates
remove duplicate rows
keep the first duplicate
keep the last duplicate'''
df=pd.read_csv("raw_data.csv")

In [29]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [32]:
df.duplicated().value_counts()

False    10
True      1
Name: count, dtype: int64

In [33]:
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [34]:
df.duplicated(keep="first")

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [35]:
df.duplicated(keep="last")

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [1]:
'''12. apply(), map() and replace()

Given a marks column:

[35, 45, 67, 89, 92]

Use Pandas operations to:

create Pass/Fail
convert marks into grades
replace specific values

Understand the difference between apply(), map(), and replace().'''
import pandas as pd
df=pd.DataFrame([35, 45, 67, 89, 92],columns=["Marks"])
x=[35, 45, 67, 89, 92]

In [2]:
df1=df["Marks"].apply(lambda x:"pass" if x>50 else "fail")
df1

0    fail
1    fail
2    pass
3    pass
4    pass
Name: Marks, dtype: str

In [3]:
x=[35, 45, 67, 89, 92]
def grade(m):
    if m>=90:
        return 'A'
    elif m>60:
        return 'B'
    elif m>40:
        return 'C'
    elif m<=35:
        return 'D'
    else:
        return 'E'

grades=list(map(grade,x))
print(grades)

['D', 'C', 'B', 'B', 'A']

In [4]:
df2=pd.DataFrame(grades,columns=["Marks"])

In [5]:
df2

  Marks
0     D
1     C
2     B
3     B
4     A

In [6]:
df2['Marks']=df2['Marks'].replace({"A":"B","B":"C","C":"D","D":"E"})

##

In [7]:
df2

  Marks
0     E
1     D
2     C
3     C
4     B

In [8]:
'''13. String Operations

Given a column:

["Deepak", "Rahul", "Amit", "rohit"]

Use Pandas string functions to:

convert all names to uppercase
convert to lowercase
find string length
check whether a name starts with a particular letter
replace part of a string'''
y=["Deepak", "Rahul", "Amit", "rohit"]
df=pd.DataFrame(y,columns=["Name"])

In [29]:
df["Name"]=df["Name"].str.upper()

In [30]:
df["Name"].str.lower()

0    deepak
1     rahul
2      amit
3     rohit
Name: Name, dtype: str

In [31]:
df['length']=df['Name'].str.len()

In [32]:
df

     Name  length
0  DEEPAK       6
1   RAHUL       5
2    AMIT       4
3   ROHIT       5

In [37]:
df['Name']=df['Name'].str.replace({"R":"A","I":"E"})

In [38]:
df

     Name  length
0  DEEPAK       6
1   AAHUL       5
2    AMET       4
3   AOHET       5

In [40]:
df['Name']=df['Name'].str.startswith('A')

In [41]:
df

    Name  length
0  False       6
1   True       5
2   True       4
3   True       5

In [42]:
'''14. Unique Values and Value Counts

Given a column:

["Delhi", "Jaipur", "Delhi", "Mumbai", "Jaipur", "Delhi"]

Find:

unique cities
number of unique cities
frequency of each city
most frequently occurring city'''
city=["Delhi", "Jaipur", "Delhi", "Mumbai", "Jaipur", "Delhi"]
df=pd.DataFrame(city,columns=["city"])

In [44]:
df['city'].unique()

<ArrowStringArray>
['Delhi', 'Jaipur', 'Mumbai']
Length: 3, dtype: str

In [45]:
df['city'].nunique()

3

In [46]:
df['city'].value_counts()

city
Delhi     3
Jaipur    2
Mumbai    1
Name: count, dtype: int64

In [47]:
'''15. GroupBy

Given sales data containing:

Employee | Department | Sales

Use groupby() to find:

total sales by department
average sales by department
maximum sales by department
number of employees in each department'''
data = {
    "Employee": [
        "Amit", "Rahul", "Priya", "Neha", "Amit",
        "Rahul", "Priya", "Neha", "Amit", "Rahul"
    ],
    "Department": [
        "IT", "IT", "HR", "HR", "IT",
        "Sales", "Sales", "HR", "Sales", "Sales"
    ],
    "Sales": [
        50000, 60000, 45000, 55000, 70000,
        65000, 75000, 50000, 80000, 70000
    ]
}
df=pd.DataFrame(data)

In [48]:
df

  Employee Department  Sales
0     Amit         IT  50000
1    Rahul         IT  60000
2    Priya         HR  45000
3     Neha         HR  55000
4     Amit         IT  70000
5    Rahul      Sales  65000
6    Priya      Sales  75000
7     Neha         HR  50000
8     Amit      Sales  80000
9    Rahul      Sales  70000

In [56]:
df['Sales'].sum()

np.int64(620000)

In [53]:
df.groupby("Department")["Sales"].sum()

Department
HR       150000
IT       180000
Sales    290000
Name: Sales, dtype: int64

In [57]:
df.groupby("Department")["Sales"].max()

Department
HR       55000
IT       70000
Sales    80000
Name: Sales, dtype: int64

In [58]:
df.groupby("Department")["Employee"].count()

Department
HR       3
IT       3
Sales    4
Name: Employee, dtype: int64

In [59]:
'''16. Merge and Join

Create two DataFrames:

Customer
Customer_ID | Name

and

Order
Customer_ID | Amount

Perform:

inner join
left join
right join
outer join

Understand when each join is used.'''
customers = pd.DataFrame({
    "Customer_ID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Rahul", "Priya", "Neha", "Ravi"],
    "City": ["Jaipur", "Delhi", "Mumbai", "Pune", "Kota"]
})
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer_ID": [101, 102, 101, 103, 106, 104],
    "Amount": [5000, 3000, 7000, 4500, 6000, 2500]
})

In [60]:
customers

   Customer_ID   Name    City
0          101   Amit  Jaipur
1          102  Rahul   Delhi
2          103  Priya  Mumbai
3          104   Neha    Pune
4          105   Ravi    Kota

In [61]:
orders

   Order_ID  Customer_ID  Amount
0      1001          101    5000
1      1002          102    3000
2      1003          101    7000
3      1004          103    4500
4      1005          106    6000
5      1006          104    2500

In [62]:
(pd.merge)(customers,orders,on='Customer_ID')

   Customer_ID   Name    City  Order_ID  Amount
0          101   Amit  Jaipur      1001    5000
1          101   Amit  Jaipur      1003    7000
2          102  Rahul   Delhi      1002    3000
3          103  Priya  Mumbai      1004    4500
4          104   Neha    Pune      1006    2500

In [63]:
(pd.merge)(customers,orders,on='Customer_ID',how='left')

   Customer_ID   Name    City  Order_ID  Amount
0          101   Amit  Jaipur    1001.0  5000.0
1          101   Amit  Jaipur    1003.0  7000.0
2          102  Rahul   Delhi    1002.0  3000.0
3          103  Priya  Mumbai    1004.0  4500.0
4          104   Neha    Pune    1006.0  2500.0
5          105   Ravi    Kota       NaN     NaN

In [64]:
(pd.merge)(customers,orders,on='Customer_ID',how='right')

   Customer_ID   Name    City  Order_ID  Amount
0          101   Amit  Jaipur      1001    5000
1          102  Rahul   Delhi      1002    3000
2          101   Amit  Jaipur      1003    7000
3          103  Priya  Mumbai      1004    4500
4          106    NaN     NaN      1005    6000
5          104   Neha    Pune      1006    2500

In [66]:
df3=(pd.merge)(customers,orders,on='Customer_ID',how='outer')

In [67]:
df3

   Customer_ID   Name    City  Order_ID  Amount
0          101   Amit  Jaipur    1001.0  5000.0
1          101   Amit  Jaipur    1003.0  7000.0
2          102  Rahul   Delhi    1002.0  3000.0
3          103  Priya  Mumbai    1004.0  4500.0
4          104   Neha    Pune    1006.0  2500.0
5          105   Ravi    Kota       NaN     NaN
6          106    NaN     NaN    1005.0  6000.0

In [73]:
'''17. Concatenation

Create two DataFrames containing employee information and combine them:

row-wise
column-wise

Use pd.concat() and explain the difference between axis=0 and axis=1.'''
pd.concat([customers,orders],ignore_index=True)

    Customer_ID   Name    City  Order_ID  Amount
0           101   Amit  Jaipur       NaN     NaN
1           102  Rahul   Delhi       NaN     NaN
2           103  Priya  Mumbai       NaN     NaN
3           104   Neha    Pune       NaN     NaN
4           105   Ravi    Kota       NaN     NaN
5           101    NaN     NaN    1001.0  5000.0
6           102    NaN     NaN    1002.0  3000.0
7           101    NaN     NaN    1003.0  7000.0
8           103    NaN     NaN    1004.0  4500.0
9           106    NaN     NaN    1005.0  6000.0
10          104    NaN     NaN    1006.0  2500.0

In [75]:
pd.concat([customers,orders],axis=1)

   Customer_ID   Name    City  Order_ID  Customer_ID  Amount
0        101.0   Amit  Jaipur      1001          101    5000
1        102.0  Rahul   Delhi      1002          102    3000
2        103.0  Priya  Mumbai      1003          101    7000
3        104.0   Neha    Pune      1004          103    4500
4        105.0   Ravi    Kota      1005          106    6000
5          NaN    NaN     NaN      1006          104    2500

In [83]:
'''18. Pivot Table and Crosstab

Given sales data containing:

Region | Product | Sales

Create a pivot table showing sales by region and product.

Then use pd.crosstab() to count categorical combinations.'''
import pandas as pd

df = pd.DataFrame({
    "Region": [
        "North", "North", "North",
        "South", "South", "South",
        "East", "East", "East",
        "West", "West", "West"
    ],
    "Product": [
        "Laptop", "Mobile", "Tablet",
        "Laptop", "Mobile", "Tablet",
        "Laptop", "Mobile", "Tablet",
        "Laptop", "Mobile", "Tablet"
    ],
    "Sales": [
        75000, 50000, 28000,
        65000, 45000, 32000,
        70000, 40000, 25000,
        95000, 60000, 35000
    ]
})

In [84]:
df

   Region Product  Sales
0   North  Laptop  75000
1   North  Mobile  50000
2   North  Tablet  28000
3   South  Laptop  65000
4   South  Mobile  45000
5   South  Tablet  32000
6    East  Laptop  70000
7    East  Mobile  40000
8    East  Tablet  25000
9    West  Laptop  95000
10   West  Mobile  60000
11   West  Tablet  35000

In [85]:
#df2['Region'].dropduplicated()
df2=df.pivot(
    index='Region',
    columns='Product',
    values='Sales'

)

In [86]:
df2

Product  Laptop  Mobile  Tablet
Region
East      70000   40000   25000
North     75000   50000   28000
South     65000   45000   32000
West      95000   60000   35000

In [98]:
melted=df.melt(
    id_vars='Region',
    value_vars=["Product","Sales"],
    var_name='Metrics',
    value_name='values'
)

In [99]:
melted

   Region  Metrics  values
0   North  Product  Laptop
1   North  Product  Mobile
2   North  Product  Tablet
3   South  Product  Laptop
4   South  Product  Mobile
5   South  Product  Tablet
6    East  Product  Laptop
7    East  Product  Mobile
8    East  Product  Tablet
9    West  Product  Laptop
10   West  Product  Mobile
11   West  Product  Tablet
12  North    Sales   75000
13  North    Sales   50000
14  North    Sales   28000
15  South    Sales   65000
16  South    Sales   45000
17  South    Sales   32000
18   East    Sales   70000
19   East    Sales   40000
20   East    Sales   25000
21   West    Sales   95000
22   West    Sales   60000
23   West    Sales   35000

In [3]:
'''19. Date and Time

Given:

["2026-01-15", "2026-02-20", "2026-03-10"]

Convert the column into datetime and extract:

year
month
day
day of week

Then filter records belonging to a particular month.'''
import pandas as pd
date=["2026-01-15", "2026-02-20", "2026-03-10"]
df=pd.DataFrame(date,columns=['Dates'])

In [22]:
type(df)

pandas.DataFrame

In [23]:
df['Dates']=pd.to_datetime(df['Dates'])

In [28]:
df.dtypes

Dates    datetime64[us]
dtype: object

In [29]:
df['year']=df['Dates'].dt.year

In [31]:
df['month']=df['Dates'].dt.month

In [32]:
df

       Dates  year  month
0 2026-01-15  2026      1
1 2026-02-20  2026      2
2 2026-03-10  2026      3

In [33]:
df['day']=df['Dates'].dt.day

In [34]:
df

       Dates  year  month  day
0 2026-01-15  2026      1   15
1 2026-02-20  2026      2   20
2 2026-03-10  2026      3   10

In [36]:
df[df['Dates']=='2026-02-20']

       Dates  year  month  day
1 2026-02-20  2026      2   20

In [48]:
df[df['day']==10]

       Dates  year  month  day
2 2026-03-10  2026      3   10

In [49]:
'''20. Mini Data Cleaning + Analysis Problem

Given a CSV containing:

CustomerID
Name
Age
Gender
City
Income
PurchaseAmount


load the CSV
inspect the data
check data types
check missing values
remove duplicates
handle missing values
filter customers based on income
calculate average purchase amount
find the highest-spending customer
find city-wise average purchase
find gender-wise average income
sort customers by purchase amount
create a new category based on purchase amount
save the cleaned DataFrame as a new CSV'''

'20. Mini Data Cleaning + Analysis Problem\n\nGiven a CSV containing:\n\nCustomerID\nName\nAge\nGender\nCity\nIncome\nPurchaseAmount\nload the CSV\ninspect the data\ncheck data types\ncheck missing values\nremove duplicates\nhandle missing values\nfilter customers based on income\ncalculate average purchase amount\nfind the highest-spending customer\nfind city-wise average purchase\nfind gender-wise average income\nsort customers by purchase amount\ncreate a new category based on purchase amount\nsave the cleaned DataFrame as a new CSV'

In [1]:
import pandas as pd
df=pd.read_csv("raw_data.csv")

In [2]:
df.shape

(11, 6)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     str
 2   age      8 non-null      float64
 3   country  10 non-null     str
 4   gender   10 non-null     str
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), str(3)
memory usage: 849.0 bytes

In [4]:
df.size

66

In [7]:
df.describe()

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [8]:
df.columns

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='str')

In [9]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [10]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [11]:
df=df.drop_duplicates()

In [12]:
df.reset_index(drop=True)

   id          name   age country   gender   income
0   1      John Doe  29.0     USA     Male  55000.0
1   2    Jane Smith   NaN  Canada   Female  62000.0
2   3          Alex   NaN     USA  Unknown  47000.0
3   4  Maria Garcia  34.0   Spain   Female      NaN
4   5        Li Wei  27.0   China     Male  51000.0
5   6           NaN  45.0   India   Female  73000.0
6   7    Ahmed Khan  38.0     NaN     Male  68000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   9   Carlos Ruiz   NaN  Mexico     Male  45000.0
9  10   Emily Davis  31.0     USA      NaN  58000.0

In [13]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [15]:
df['age']=df['age'].fillna(df['age'].mean())

In [16]:
df['income']=df['income'].fillna(df['income'].mean())

In [19]:
df1=df.dropna()

In [21]:
df1

   id          name        age country   gender        income
0   1      John Doe  29.000000     USA     Male  55000.000000
2   2    Jane Smith  33.285714  Canada   Female  62000.000000
3   3          Alex  33.285714     USA  Unknown  47000.000000
4   4  Maria Garcia  34.000000   Spain   Female  57888.888889
5   5        Li Wei  27.000000   China     Male  51000.000000
8   8    Rachel Lee  29.000000     USA   Female  62000.000000
9   9   Carlos Ruiz  33.285714  Mexico     Male  45000.000000

In [28]:
df1.groupby("country")["income"].mean()

country
Canada    62000.000000
China     51000.000000
Mexico    45000.000000
Spain     57888.888889
USA       54666.666667
Name: income, dtype: float64

In [29]:
df1['income'].mean()

np.float64(54269.841269841265)

In [32]:
df1["income"].max()

np.float64(62000.0)

In [34]:
df1.groupby("gender")["income"].mean()

gender
Female     60629.629630
Male       50333.333333
Unknown    47000.000000
Name: income, dtype: float64

In [43]:
sorted=df1.sort_values('income')

In [54]:
s1=sorted.reset_index(drop=True)

In [56]:
s2=s1.drop(['id'],axis=1)

In [57]:
s2

           name        age country   gender        income
0   Carlos Ruiz  33.285714  Mexico     Male  45000.000000
1          Alex  33.285714     USA  Unknown  47000.000000
2        Li Wei  27.000000   China     Male  51000.000000
3      John Doe  29.000000     USA     Male  55000.000000
4  Maria Garcia  34.000000   Spain   Female  57888.888889
5    Jane Smith  33.285714  Canada   Female  62000.000000
6    Rachel Lee  29.000000     USA   Female  62000.000000

In [58]:
s2=s2.to_csv("cleaned_data.csv")